### ISSUE TITLE
ErrorException: A non-numeric value encountered:

### ISSUE THREAD

**Issue by i386** [stackkit/laravel-google-cloud-tasks-queue#105]
We sometimes see this error `ErrorException: A non-numeric value encountered` in production.

I suspect we are passing a `null` to the `->delay(time)` when queueing a job somewhere. Ill get around to submitting a PR to tell us which job name and what the non-numeric value actually is.

```
 PHP Notice: ErrorException: A non-numeric value encountered in /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Units.php:136
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Units.php(136): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Date.php(2661): Carbon\Carbon->addRealUnit()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php(37): Carbon\Carbon->__call()
#4 /var/www/html/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php(136): Illuminate\Queue\Queue->availableAt()
#5 /var/www/html/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php(119): Stackkit\LaravelGoogleCloudTasksQueue\CloudTasksQueue->pushToCloudTasks()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(315): Stackkit\LaravelGoogleCloudTasksQueue\CloudTasksQueue->Stackkit\LaravelGoogleCloudTasksQueue\{closure}()
#7 /var/www/html/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php(60): Illuminate\Queue\Queue->enqueueUsing()
#8 /var/www/html/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php(113): Stackkit\LaravelGoogleCloudTasksQueue\CloudTasksQueue->enqueueUsing()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(71): Stackkit\LaravelGoogleCloudTasksQueue\CloudTasksQueue->later()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(242): Illuminate\Queue\Queue->laterOn()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\Bus\Dispatcher->pushCommandToQueue()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\Bus\Dispatcher->dispatchToQueue()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\Bus\Dispatcher->dispatch()
#14 /var/www/html/app/Services/Notification/NotificationService.php(63): Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#15 /var/www/html/app/Services/Notification/NotificationService.php(52): App\Services\Notification\NotificationService->queueTask()
#16 /var/www/html/app/Console/Commands/MessagesSchedulePendingTasks.php(20): App\Services\Notification\NotificationService->schedulePendingTasks()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\MessagesSchedulePendingTasks->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\Container\Container->call()
#23 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\Component\Console\Command\Command->run()
#25 /var/www/html/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#26 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#27 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(162): Symfony\Component\Console\Application->run()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(381): Illuminate\Console\Application->call()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\Foundation\Console\Kernel->call()
#31 /var/www/html/app/Console/Commands/MessagesTasks.php(26): Illuminate\Support\Facades\Facade::__callStatic()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\MessagesTasks->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\Container\Container->call()
#38 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\Component\Console\Command\Command->run()
#40 /var/www/html/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#41 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#42 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\Component\Console\Application->run()
#44 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#45 {main} 
```

**Comment by marickvantuil** [comment]
Yes, please let me know. If I pass `null` (to `delay()`) it seems to work and when I pass a numeric string it also works fine, but a string 'a' errors: Unsupported operand types: int + string
