### ISSUE TITLE
500 Server Error when Cloud Task push HTTP request

### ISSUE THREAD

**Issue by wildangunawan** [stackkit/laravel-google-cloud-tasks-queue#33]
Hi there,

I've an issue with the Cloud Task. All work fine for inputting the task to Cloud Task (CT), but when CT push HTTP request, I got 500 server error.

Here's the payload from CT:
```
{"uuid":"c8e8f331-1241-4fe4-881b-8fc842d0ac6e","displayName":"App\\Notifications\\EmailVerificationNotification","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"maxExceptions":null,"failOnTimeout":false,"backoff":"","timeout":null,"retryUntil":null,"data":{"commandName":"Illuminate\\Notifications\\SendQueuedNotifications","command":"O:48:\"Illuminate\\Notifications\\SendQueuedNotifications\":16:{s:11:\"notifiables\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:15:\"App\\Models\\User\";s:2:\"id\";a:1:{i:0;C:35:\"Ramsey\\Uuid\\Lazy\\LazyUuidFromString\":36:{227d35ff-bfe5-4fbb-9f88-6a73ec12a155}}s:9:\"relations\";a:0:{}s:10:\"connection\";s:5:\"mysql\";}s:12:\"notification\";O:47:\"App\\Notifications\\EmailVerificationNotification\":11:{s:2:\"id\";s:36:\"abe3e51b-c069-41a1-9e6a-6be930415050\";s:6:\"locale\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:19:\"chainCatchCallbacks\";N;s:5:\"delay\";N;s:11:\"afterCommit\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}s:8:\"channels\";a:1:{i:0;s:4:\"mail\";}s:5:\"tries\";N;s:7:\"timeout\";N;s:17:\"shouldBeEncrypted\";b:0;s:3:\"job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:19:\"chainCatchCallbacks\";N;s:5:\"delay\";N;s:11:\"afterCommit\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}"}}
```

Here's what the error returned from logging:
```
ErrorException: Illegal offset type in isset or empty in /srv/app/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1498
Stack trace:
#0 /srv/app/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1498): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal offset ...', '/srv/app/vendor...', 1498, Array)
#1 /srv/app/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(87): Illuminate\Support\Collection->offsetExists(Object(Ramsey\Uuid\Lazy\LazyUuidFromString))
#2 [internal function]: Illuminate\Notifications\SendQueuedNotifications->Illuminate\Queue\{closure}(Object(Ramsey\Uuid\Lazy\LazyUuidFromString), 0)
#3 /srv/app/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#4 /srv/app/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(88): Illuminate\Support\Collection->map(Object(Closure))
#5 /srv/app/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(56): Illuminate\Notifications\SendQueuedNotifications->restoreCollection(Object(Illuminate\Contracts\Database\ModelIdentifier))
#6 /srv/app/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(122): Illuminate\Notifications\SendQueuedNotifications->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#7 [internal function]: Illuminate\Notifications\SendQueuedNotifications->__unserialize(Array)
#8 /srv/app/vendor/stackkit/laravel-google-cloud-tasks-queue/src/TaskHandler.php(43): unserialize('O:48:"Illuminat...')
#9 /srv/app/vendor/stackkit/laravel-google-cloud-tasks-queue/src/TaskHandler.php(32): Stackkit\LaravelGoogleCloudTasksQueue\TaskHandler->loadQueueConnectionConfiguration(Array)
#10 /srv/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Stackkit\LaravelGoogleCloudTasksQueue\TaskHandler->handle(Array)
#11 /srv/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Stackkit\LaravelGoogleCloudTasksQueue\TaskHandler), 'handle')
#12 /srv/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#13 /srv/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Routing\Route->run()
#14 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /srv/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /srv/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#18 /srv/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#19 /srv/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#22 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /srv/app/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /srv/app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /srv/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 /srv/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#39 /srv/app/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#40 /srv/app/server.php(21): require_once('/srv/app/public...')
#41 {main}
```

AFAIK, it tells us that there is an error when unserializing (#8) the payload given. I don't know any further yet.

Any clue to fix this?

**Comment by wildangunawan** [comment]
Ah nevermind, my bad. It's actually not related to this package. When I run queue:work manually, it also throws the same error. So not related to this package, therefore I'm closing this issue.

Ps. I haven't find anyway to fix it though.
