### ISSUE TITLE
Audience does not match

### ISSUE THREAD

**Issue by atrauzzi** [stackkit/laravel-google-cloud-tasks-queue#63]
If I look at [this code here](https://github.com/stackkit/laravel-google-cloud-tasks-queue/blob/master/src/OpenIdVerificatorConcrete.php#L12-L25), it seems as though after the [`3.x` change to remove `/handle-task`](https://github.com/stackkit/laravel-google-cloud-tasks-queue/blob/master/UPGRADING.md#update-handler-url-impact-high) from the configs, it's not being subsequently appended when constructing the URL to perform the audience check.

This results in the following exception:

```
Audience does not match {"exception":"[object] (UnexpectedValueException(code: 0): Audience does not match at /var/www/html/vendor/google/auth/src/AccessToken.php:271)
Default
2022-08-04T15:41:41.077832Z[stacktrace]
Default
2022-08-04T15:41:41.077841Z#0 /var/www/html/vendor/google/auth/src/AccessToken.php(134): Google\\Auth\\AccessToken->verifyRs256('eyJhbGciOiJSUzI...', Array, 'https://ca-api-...', NULL)
Default
2022-08-04T15:41:41.077848Z#1 /var/www/html/vendor/stackkit/laravel-google-cloud-tasks-queue/src/OpenIdVerificatorConcrete.php(21): Google\\Auth\\AccessToken->verify('eyJhbGciOiJSUzI...', Array)
Default
2022-08-04T15:41:41.077855Z#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Stackkit\\LaravelGoogleCloudTasksQueue\\OpenIdVerificatorConcrete->verify('eyJhbGciOiJSUzI...', Array)
Default
2022-08-04T15:41:41.077861Z#3 /var/www/html/vendor/stackkit/laravel-google-cloud-tasks-queue/src/TaskHandler.php(49): Illuminate\\Support\\Facades\\Facade::__callStatic('verify', Array)
```

Shouldn't `/handle-task` be getting appended somewhere in here to ensure that it matches the `aud` URI in the JWT that google cloud tasks sends in?

**Comment by marickvantuil** [comment]
Hi @atrauzzi 

The OpenIdVerificator verifies the audience:
```php
'audience' => app('queue')->getHandler(),
```

which goes to the `CloudTasksQueue::getHandler()`

```php
public function getHandler(): string
{
    return Config::getHandler($this->config['handler']);
}
```

which in turn returns the URL with 'handle-task' appended

![Screenshot 2022-08-05 at 11 26 38](https://user-images.githubusercontent.com/647007/183047935-136729b4-12ef-4fc4-99ef-0450a2bd76d2.jpg)


Therefore, I'm not sure how this can happen? Or am I perhaps overlooking something?
